version: '3.7'

services:
  main:
    container_name: nodejs-course
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    entrypoint: ['tail', '-f', '/dev/null']
    env_file:
      - .env
    networks:
      - webnet
networks:
  webnet:
