version: '3.7'

services:
  main:
    container_name: nodejs-course
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    entrypoint: ['tail', '-f', '/dev/null']
    env_file:
      - .env
    networks:
      - webnet
  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - /data/db
    networks:
      - webnet
networks:
  webnet:
